# Generated by Django 5.2.7 on 2025-10-24 22:15

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clinic.models.drug_image_path),
        ),
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in NGN (₦)', max_digits=10),
        ),
    ]
