# Generated by Django 5.2.7 on 2025-10-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_order_reference'),
        ('clinic', '0006_auto_20251027_1949'),
    ]

    operations = [
    ]
